docs: add Core Mobile, Core Extension and Avalanche JS v4.0 audits
ava-labs/audits pull request #5
Opened 2024-03-28 18:55 UTC by gergelylovas

2024-03-29 10:34 UTC, akly approved these changes

2024-04-16 14:08 UTC, akly requested changes
Please upload the updated Mobile Wallet audit report

2024-04-17 14:56 UTC, akly approved these changes
Approved updated docs

2024-04-17 14:56 UTC, akly commented on core/Core_Mobile_Wallet_Audit_Least_Authority_November_2023.pdf
Please update this file to the latest version dated 2024 Apr 12

2024-04-17 14:56 UTC, akly commented on core/Core_Mobile_Wallet_Audit_Least_Authority_November_2023.pdf
Thanks. Please also update file name to ..._April_2024.pdf .

2024-04-17 14:56 UTC, akly commented on README.md
> +- [Least Authority Audit (November 30th 2023)](./core/Core_Mobile_Wallet_Audit_Least_Authority_November_2023.pdf)
Please update filename to match new date of the report (April 2024)

2024-04-18 15:05 UTC, akly commented
@JacobEverly can you please merge this PR if you're happy to do so?

2024-04-19 13:39 UTC, JacobEverly approved these changes

2024-04-19 14:28 UTC, StephenButtolph approved these changes

2024-04-19 14:28 UTC, merged

2025-05-28 20:35 UTC, Tawabsadat approved these changes